module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '.',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/**/*.(t|j)s',
    '!src/**/*.module.ts',
    '!src/**/*.interface.ts',
    '!src/**/*.enum.ts',
    '!src/**/*.dto.ts',
    '!src/**/*.entity.ts',
    '!src/**/*.config.ts',
    '!src/main.ts',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'clover', 'html'],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
    './src/views/extensions/asset-path.extension.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
  },
  testEnvironment: 'node',
  setupFilesAfterEnv: ['<rootDir>/src/test/setup.ts'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@shared/(.*)$': '<rootDir>/src/shared/$1',
    '^@modules/(.*)$': '<rootDir>/src/modules/$1',
    '^@config/(.*)$': '<rootDir>/src/shared/config/$1',
    '^@utils/(.*)$': '<rootDir>/src/shared/utils/$1',
    '^@services/(.*)$': '<rootDir>/src/shared/services/$1',
    '^@middleware/(.*)$': '<rootDir>/src/shared/middleware/$1',
    '^@controllers/(.*)$': '<rootDir>/src/shared/controllers/$1',
    '^@filters/(.*)$': '<rootDir>/src/shared/filters/$1',
    '^@interceptors/(.*)$': '<rootDir>/src/shared/interceptors/$1',
    '^@guards/(.*)$': '<rootDir>/src/shared/guards/$1',
    '^@decorators/(.*)$': '<rootDir>/src/shared/decorators/$1',
    '^@types/(.*)$': '<rootDir>/src/types/$1',
    '^@test/(.*)$': '<rootDir>/src/test/$1',
    '^@views/(.*)$': '<rootDir>/src/views/$1',
    '^@adapters/(.*)$': '<rootDir>/src/adapters/$1',
    '^@cache/(.*)$': '<rootDir>/src/cache/$1',
    '^@logger/(.*)$': '<rootDir>/src/logger/$1',
  },
  testTimeout: 30000,
  verbose: true,
  detectOpenHandles: true,
  forceExit: true,
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
  testPathIgnorePatterns: [
    '/node_modules/',
    '/tests/',
    '/e2e/',
    '/tests-examples/',
  ],
};
