blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: NestJS Documentation
    url: https://docs.nestjs.com/
    about: Official NestJS documentation and guides.
  - name: GOV.UK Frontend
    url: https://design-system.service.gov.uk/
    about: GOV.UK Design System documentation.
