name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # Use Node.js setup with caching
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
    
    # Install dependencies with a clean install
    - name: Install dependencies
      run: |
        npm ci
        npm cache clean --force
    
    # Install Playwright browsers with dependencies
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    # Build the application first
    - name: Build application
      run: |
        npm run build:frontend:dev
        npm run build
    
    # Run Playwright tests with increased timeout and better error handling
    - name: Run Playwright tests
      run: |
        # Set CI environment variable
        export CI=true
        # Run tests with increased timeout and verbose output
        npx playwright test --timeout=300000 --reporter=line
      env:
        CI: true
        NODE_ENV: production
    
    # Upload test results on failure
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    
    # Upload test results on success (for debugging)
    - uses: actions/upload-artifact@v4
      if: success()
      with:
        name: playwright-report-success
        path: playwright-report/
        retention-days: 7
